---
# Playbook to test : 1) API call to AAP 2) Extra vars
- name: Test API Call
  hosts: "{{ hostname }}"  # To be tested with extra variables?
  gather_facts: false

  tasks:
    - name: Printing something
      ansible.builtin.debug: 
        msg:
          - "Confirming API works"
      ignore_errors: true

    - name: Test incoming extra variables
      ansible.builtin.debug: 
        msg:
          - "Variable_1 = {{ extra_var_1 }}"
          - "Variable_2 = {{ extra_var_2 }}"
          - "Variable_3 = {{ extra_var_3 }}"
      ignore_errors: true

    - name: Printing something
      ansible.builtin.debug: 
        msg:
          - "End of tests tasks"
      ignore_errors: true
