---
# Playbook to test : 1) API call to AAP 2) Extra vars
- name: Test API Call
  hosts: linux-devices # Should be in the AAP inventory or Inventory-as-code
  gather_facts: false

  tasks:
    - name: Printing something
      ansible.builtin.debug: 
        msg:
          - "Confirming API works"
      vars:
        ansible_host: "{{ hostname }}"  # A value coming in from API Call
      ignore_errors: true

    - name: Test incoming extra variables
      ansible.builtin.debug: 
        msg:
          - "Variable_1 = {{ extra_var_1 }}"
          - "Variable_2 = {{ extra_var_2 }}"
      delegate_to: localhost
      ignore_errors: true

    - name: Get python3 version
      ansible.builtin.command:
        cmd: "{{ cmd_to_run }}"
      vars:
        ansible_host: "{{ hostname }}"
      register: command_output
      ignore_errors: true

    - name: Printing output
      ansible.builtin.debug: 
        var: command_output
      delegate_to: localhost
      ignore_errors: true
